### ISSUE TITLE
Tournaments: Double Elim loser not advancing in a bye

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#63] opened 2018-12-01 21:14 UTC
**Bug Subsystem**:  Double Elimination Tournament

**Expected Behavior:** When a team is in the Losers bracket of a DE tourney, if they are in a bye the site should automatically advance them.

**Actual Behavior:** The team is not automatically advanced in a Bye game of a loser bracket match of a DE tourney.

**Reproduction Steps**: 
1. Reported test37 team losing to test33 team in ABtourney
2. test37 is shifted to the first round of the loser bracket and faces a Bye. They are not automatically advanced.

**Screenshots:** 
![screen shot 2018-12-01 at 4 12 01 pm](https://user-images.githubusercontent.com/28234097/49332915-e10c4a00-f583-11e8-82c9-728f7fb20237.png)

**Additional Information:** 
This is happening on multiple occasions in this tourney as it's easily reproducible. There is no error showing in the console for this either.

**Test Plan:**
Steps to make sure that this is working
Note: Leave this blank unless you are the developer who fixed this
Note: Do not check things unless you are the assigned tester

**Comment by SkirmishPro** [comment] 2018-12-02 21:39
Just tested this in a brand new tournament and it looks like this is still an issue. Check out the "ABtouney 2" to see it.

![screen shot 2018-12-02 at 4 38 41 pm](https://user-images.githubusercontent.com/28234097/49345295-ca7ff480-f650-11e8-9feb-0a8a3449872f.png)

**Comment by SkirmishPro** [comment] 2018-12-02 22:13
Seems like this is still an issue. Check out my tourney "ABtourney 3". What's weird is when I test this in your "Testing Twitch Integration" tournament, it works fine. The user who is up against the bye in the losers bracket advances automatically, it's not working in my tourney though which I think is because it's a team tourney vs a 1v1 tourney.

![screen shot 2018-12-02 at 5 11 23 pm](https://user-images.githubusercontent.com/28234097/49345626-83483280-f655-11e8-9319-8d4cde20ec2d.png)

**Comment by KyleKaniecki** [comment] 2018-12-03 15:35
I will check this out when I get home tonight.

**Comment by KyleKaniecki** [comment] 2018-12-05 18:38
I cannot reproduce this locally. Everything works as intended.

It may be because the bracket was generated using old code and won't work with the new code. That shouldn't be the case, but it is just a thought. I would try creating brand new brackets and see how that affects things. If things are working as intended, I would say this is done.

**Comment by KyleKaniecki** [comment] 2018-12-11 19:57
Finally able to reproduce this locally. I will look into why this is not working as intended.

**Comment by KyleKaniecki** [comment] 2018-12-11 20:12
Lol figures, it was just a small typo. Will fix this when I get home.

**Comment by KyleKaniecki** [comment] 2018-12-12 20:18
Fixed. Closing.

**Closed as completed by KyleKaniecki** 2018-12-12 20:18 UTC
Labels: bug, web, Tournaments
