### ISSUE TITLE
Skirm Creation with Restricted States

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#35] opened 2018-07-03 22:08 UTC
**Bug Subsystem**: 
1v1 and Team Skirm

**Expected Behavior:** 
Even if I'm verified, if I'm in a restricted state i should not be able to create a 1v1 or team skirm with a pledge.

**Actual Behavior:** 
I'm able to create a 1v1 and team Skirm with a player in AZ.

**Reproduction Steps**: 
1. I set test3 as verified and from Arizona
2. I was able to create a 1v1 and team Skirm with a $5 pledge (the payments for both Skirms were created but did not process).

**Screenshots:** 
N/A

**Additional Information:** 
The team I used for testing had test4 on the roster who is also in a different restricted state (PA).

**Comment by KyleKaniecki** [comment] 2018-07-03 23:22
So this is actually **working as intended.**

Since the verified flag is the single commandment on our site, that is the **sole** thing that I look for when allowing people to create paid games. Since test3 is from Arizona, they should have never been verified in the first place. This is admin/user error, and not a bug on the api. Closing as won't fix.

**Closed as completed by KyleKaniecki** 2018-07-03 23:22 UTC
Labels: bug, web, wontdo, Skirms
