### ISSUE TITLE
Editing a 1v1 tournament

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#8] opened 2018-05-01 14:14 UTC
**Bug Subsystem**: Tournaments

**Expected Behavior:** 
If a tournament admin/host decides to edit their already posted tournament in which the registration deadline has passed to increase the number of entrants allowed, let's say from 16 to 17, the tournament should reflect those changes but still hold the deadline permissions ie. registering and checking in. In other words, changes to a tournament should not affect the permissions for registering and checking in.

**Actual Behavior:** 
If an admin/host decides to edit a tournament, the register and check-in button appear when they should. For example, the screenshot below has the check-in button available to test1 however the registration deadline has not passed (you'll notice the time I took the screenshot was before 10am. I set the registration deadline at 10am).

I also created, registered, checked-in, then edited "AB Test 8" to increase the number of entrants from 3 to 4 (before the registration deadline), then 4 to 5 (after the registration deadline and after players checked in). I then went moved the deadline forward so that I could register test5 however the button disappeared, see the second screenshot.

**Reproduction Steps**: 

1. I created a tourney as an Admin
2. I registered players
3. The deadline passed and I checked players in. At this step I did edit AB Test 6 to increase the number of entrants and this is where I saw the first screenshot.
4. I then created a new tourney, AB Test 8
5. I registered and checked in a few players
6. After the deadline had passed I then edited the tourney to increase the number of entrants as well as move the registration deadline forward to accommodate the addition of another player. This is where I see the second screenshot. I could not add test5 even though the tournament did not have it's maximum players and the registration deadline did not pass.

**Screenshots:** 
see attached

**Additional Information:** 

![ss_1](https://user-images.githubusercontent.com/28234097/39476022-86b76ff2-4d28-11e8-9260-7a7203ae8a83.PNG)
![ss_2](https://user-images.githubusercontent.com/28234097/39476025-8be32ce6-4d28-11e8-9561-14fdb468ab5d.PNG)

**Comment by KyleKaniecki** [comment] 2018-05-01 16:11
@SkirmishPro Please double check the **dates** of the screenshots provided. Even though the registration time and start time for the tournament are after the time listed on your computer, the dates are not. This means that the player **should not** be able to do the actions you are listing above.

I believe what you are seeing though is the bug listed in issue #4. I am marking this as a duplicate. Please close if confirmed.

**Comment by KyleKaniecki** [comment] 2018-05-03 16:08
Closing due to inactivity

**Closed as completed by KyleKaniecki** 2018-05-03 16:08 UTC
Labels: bug, duplicate, web, Tournaments
